# Generated by Django 6.0.5 on 2026-07-02 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('ALUNO', 'Aluno'), ('VISITANTE', 'Visitante')], max_length=20)),
                ('matricula', models.CharField(blank=True, max_length=30, null=True)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('empresa', models.CharField(blank=True, max_length=150, null=True)),
                ('motivo_visita', models.CharField(blank=True, max_length=200, null=True)),
                ('foto', models.ImageField(upload_to='rostos/')),
                ('embedding', models.JSONField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Presenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('camera', models.CharField(default='Entrada Principal', max_length=100)),
                ('confianca', models.FloatField(default=0)),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pessoa')),
            ],
        ),
    ]
