# Generated by Django 5.2.16 on 2026-07-28 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_pessoa_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='empresa',
        ),
    ]
